Implement backward-compatible `tags` function
personio/datadog-synthetic-test-support pull request #138
Opened 2023-10-16 14:03 UTC by darmen

## Why

To support existing API for Browser tests.

2023-10-16 14:20 UTC, azzmiks requested changes
Please update the Changelog file with the changes

2023-10-16 14:20 UTC, azzmiks commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
>              tags("synthetics-api")
Does it make sense to replace this one then?

2023-10-16 15:00 UTC, akhilbv commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
> +            tags(listOf("one", "two"))
can we pass it as comma separated and handle the list inside of the function, so won't break the existing behaviour

WDYT?

2023-10-18 07:28 UTC, azzmiks commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
>              tags("synthetics-api")
It would be nice to keep the correct version only then, even despite both versions are available, so that new repos would use the correct one. Wdyt?

2023-10-18 08:48 UTC, andrebq submitted a review, later dismissed

2023-10-18 09:01 UTC, andrebq submitted a review, later dismissed

2023-10-19 12:06 UTC, azzmiks submitted a review, later dismissed

2023-10-19 12:14 UTC, arunprakashind approved these changes

2023-10-19 12:14 UTC, andrebq approved these changes

2023-10-19 12:17 UTC, merged