Prepare for Browser Test refactoring
personio/datadog-synthetic-test-support pull request #188
Opened 2024-02-01 14:30 UTC by darmen

## Why

This PR is part of an effort to split https://github.com/personio/datadog-synthetic-test-support/pull/156 into smaller, manageable and reviewable pull requests.

## Scope

The changes are preparatory to the upcoming refactoring of the Browser test implementation.

2024-02-01 14:54 UTC, azzmiks requested changes

2024-02-01 14:54 UTC, azzmiks commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
> +     * This test creates a Synthetic Browser test in Datadog.
Please remove dot in the end of the sentence for consistency

2024-02-01 14:54 UTC, azzmiks commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
> +            status(SyntheticsTestPauseStatus.PAUSED)
This is redundant

2024-02-01 14:54 UTC, azzmiks commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
> +
Please remove the waste empty line

2024-02-01 14:54 UTC, azzmiks commented on src/test/kotlin/com/personio/synthetics/e2e/E2EBrowserTest.kt
> +
Please remove the waste empty line

2024-02-01 15:10 UTC, azzmiks commented
@darmen Could you please also add a note to the Changelog file?

2024-02-01 15:47 UTC, azzmiks approved these changes

2024-02-01 15:53 UTC, darmen commented on src/main/kotlin/com/personio/synthetics/builder/SyntheticBrowserTestBuilder.kt
> +            .status(SyntheticsTestPauseStatus.PAUSED)
Changed to the actual status

2024-02-02 15:26 UTC, azzmiks commented on src/main/kotlin/com/personio/synthetics/builder/browser/StepsBuilder.kt
> +    fun typeText(
Let's keep it like this for now. I'll trigger some discussions around this but since the changes you do are anyway breaking, it's ok.

2024-02-02 15:39 UTC, azzmiks submitted a review, later dismissed

2024-02-02 15:56 UTC, friduchin commented on build.gradle.kts
> +            excludeTestsMatching("com.personio.synthetics.e2e.E2EBrowserTest.*")
Are we planning to remove this exclusion with the future iterations of refactoring?

2024-02-02 15:56 UTC, friduchin approved these changes

2024-02-06 08:06 UTC, azzmiks approved these changes

2024-02-06 09:06 UTC, azzmiks requested changes

2024-02-06 09:33 UTC, azzmiks submitted a review, later dismissed

2024-02-08 11:17 UTC, darmen commented on src/test/kotlin/com/personio/synthetics/builder/SyntheticBrowserTestBuilderTest.kt
> -    fun `status sets status of a test`() {
We need it, goot catch. Reverted.

2024-02-12 09:26 UTC, azzmiks approved these changes

2024-02-12 10:40 UTC, arunprakashind approved these changes

2024-02-12 10:41 UTC, merged